import pandas as pd


class DBManager:
    def __init__(self):
        """Initialize the 'database'"""
        # TODO: database connection happens on instance load
        # ideally defined in the config file
        # BUT for now we can hardcode it here
        # connect_to_db( host, port, username, password)

    # -----------------------
    #       PUSH DATA
    # -----------------------
    def push_new_experiment_to_db(
        self,
        user_id: int,  # returned by the db
        experiment_name: str,  # provided from UI
        time_stamp: str,  # provided from UI
        substrate_cas_number: list[str],  # provided from UI
        product_cas_number: list[str],  # provided from UI
        assay: str,  # provided from UI
        mutegenesis_method: bool,  # epPCR=0 SSM=1
        plates_count: int,  # processed
        parent_sequence: str,  # processed
        experiment_data: pd.DataFrame,  # the contents of the csv
        pdb_file: bytes,  # file uploaded from the user
        experiment_time: str = None,  # provided from UI - optional
    ) -> int:
        """
        Push a new experiment record into the database.

        This method stores an experiment in the database along with its metadata,
        processed data, and uploaded files. An experiment ID is automatically
        generated by the database and returned for future reference.

        Parameters
        ----------
        user_id : int
            Unique identifier for the user (retrieved from the database).
        experiment_name : str
            Descriptive name of the experiment (provided via the UI).
        time_stamp : str
        experiment_time : str, optional
        substrate_cas_number : list[str]
        product_cas_number : list[str]
        assay : str
        mutegenesis_method : bool
            Mutation method used, where `1` indicates SSM (site-saturation mutagenesis),
            and `0` indicates epPCR (error-prone PCR).
        plates_count : int
        parent_sequence : str
            The parent sequence extracted
        experiment_data : pd.DataFrame
            DataFrame containing the experiment data (e.g., CSV contents).
        pdb_file : bytes #TODO: should this be bytes?
            Contents of the uploaded PDB file (e.g., a structure file for proteins).

        Returns
        -------
        int
            Unique identifier for the experiment created in the database.

        """
        # TODO:push_new_experiment_to_db() stub
        return 0

    # ---------------------------
    #    Delete
    # ---------------------------
    def delete_experiment(self, experiment_id: int) -> bool:
        """
            Delete the experiment associated with this id

        Returns
        -------
            bool True if deleted successfully

        """

    # ---------------------------
    #    DATA RETRIEVAL: USER
    # ---------------------------
    def get_user_id(self, username: str, password: str) -> int:
        """
        Retrieve the unique user ID for a given username and password combination.

        Parameters
        ----------
        username : str
            The username provided by the user.
        password : str
            The password associated with the username.

        Returns
        -------
        int
            The unique user ID if the credentials are valid; otherwise, an error or None.

        """
        # TODO:get_user_id() stub
        return 0

    def get_all_users(self) -> list:
        """
        Retrieve a list of all user IDs in this lab.

        Returns
        -------
        list
            A list of unique user IDs belonging to all users in the lab.

        """
        # TODO:get_all_users() stub
        return []

    def get_user_experiments(self, user_id: str) -> pd.DataFrame:
        """
        Retrieve all experiments uploaded by a specific user.

        Parameters
        ----------
        user_id : str
            The unique ID of the user whose experiments are to be fetched.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing details about all experiments uploaded by the user, with the following columns:
            - 'experiment_name' (str):
            - 'experiment_id' (int):
            - 'time_stamp' (str):
            - 'experiment_time' (str): if available.
            - 'plates_count' (int):
            - 'substrate_cas_number' (list of str):
            - 'product_cas_number' (list of str):
            - 'assay' (str):

        """
        # TODO: get_user_experiments() stub
        return pd.DataFrame()

    def get_all_experiments(self) -> pd.DataFrame:
        """
        Retrieve all experiments uploaded by a all users.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing details about all experiments uploaded by the user, with the following columns:
            - 'user_id' (int):
            - 'user_name' (str):
            - 'experiment_name' (str):
            - 'experiment_id' (int):
            - 'time_stamp' (str):
            - 'experiment_time' (str): if available.
            - 'plates_count' (int):
            - 'substrate_cas_number' (list of str):
            - 'product_cas_number' (list of str):
            - 'assay' (str):

        """
        # TODO: get_all_experiments() stub
        return pd.DataFrame()

    # ----------------------------
    #   DATA RETRIEVAL: PER EXPERIMENT
    # ----------------------------
    def get_experiment_parent_sequence(self, experiment_id: int) -> str:
        """
        Retrieve the parent sequence associated with a specific experiment.

        Parameters
        ----------
        experiment_id : int
            The unique identifier for the experiment.

        Returns
        -------
        str
            The parent sequence of the experiment that was provided by the push function
        """
        # TODO: get_experiment_parent_sequence() stub
        return ""

    def get_experiment_pdb_file(self, experiment_id: int):
        """
        Retrieve the Protein Data Bank (PDB) file associated with a specific experiment.

        Parameters
        ----------
        experiment_id : int
            The unique identifier for the experiment.

        Returns
        -------
        bytes #TODO: bytes? I have to investigate the upload format
            The PDB file of the experiment that was provided with upload

        """
        # TODO: get_experiment_pdb_file() stub
        return None

    def get_experiment_meta_data(self, experiment_id: int) -> dict:
        """
        Retrieve metadata for a specific experiment.

        Parameters
        ----------
        experiment_id : int
            The unique identifier for the experiment.

        Returns
        -------
        dict
            A dictionary containing metadata for the experiment with the following keys:
            - 'experiment_name' (str): The name of the experiment.
            - 'time_stamp' (str): The date and time the experiment was created.
            - 'experiment_time': str
            - 'plates_count' (int): The number of plates used in the experiment.
            - 'substrate_cas_number' list: The CAS numbers of the substrate.
            - 'product_cas_number' list: The CAS numbers of the product.
            - 'assay' (str): The assay used in the experiment.
        """
        # TODO: get_experiment_meta_data() stub
        return {}

    def get_experiment_fitness_values(self, experiment_id: int) -> pd.DataFrame:
        """
        Retrieve fitness values for a specific experiment including the X and Y location

        Parameters
        ----------
        experiment_id : int
            The unique identifier for the experiment.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing following columns:
            - 'cas_number' (str):
            - 'plate' (str):
            - 'well' (str):
            - 'amino_acid_substitutions' (str):
            - 'x_coordinate' (float)':
            - 'y_coordinate' (float)' :
            - 'fitness_value' (float):
        """
        # TODO: get_experiment_fitness_values() stub
        return pd.DataFrame()

    def get_experiment_all(self, experiment_id: int) -> pd.DataFrame:
        """
        Retrieve ALL data uploaded by user in the original csv file.
        This does not include the metadata.

        Parameters
        ----------
        experiment_id : int
            The unique identifier for the experiment.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing following columns:
            - 'ID' (str):
            - 'barcode_plate' (int):
            - 'cas_number' (str):
            - 'plate' (str):
            - 'well' (str):
            - 'aligment_count' (int):
            - 'nucleotide_mutation' (str):
            - 'amino_acid_substitutions' (str):
            - 'alignment_probability' (int):
            - 'average_mutation_frequency' (int):
            - 'p_value' (int):
            - 'p_adj_value' (int):
            - 'nt_sequence' (str):
            - 'aa_sequence' (str):
            - 'average_mutation_frequency' (int):
            - 'x_coordinate' (float)':
            - 'y_coordinate' (float)' :
            - 'fitness_value' (float):
        """
        # TODO: get_experiment_all() stub
        return pd.DataFrame()

    # ----------------------------
    #   DATA RETRIEVAL: EXPERIMENT STATS
    # ----------------------------
    def get_experiment_alignment_count(self, experiment_id: int) -> pd.DataFrame:
        """
        Returns
        -------
        pd.DataFrame
            A DataFrame containing the following columns:
            - 'plate' (str):
            - 'well' (str):
            - 'alignment_count' (int):
        """
        # TODO: get_experiment_alignment_count() stub
        return pd.DataFrame()

    def get_experiment_alignment_probability(self, experiment_id: int) -> pd.DataFrame:
        """
        Returns
        -------
        pd.DataFrame
            A DataFrame containing the following probability:
            - 'plate' (str):
            - 'well' (str):
            - 'alignment_probability' (float):
        """
        # TODO: get_experiment_alignment_probability() stub
        return pd.DataFrame()

    def get_experiment_average_mutation_frequency(self, experiment_id: int) -> pd.DataFrame:
        """
        Returns
        -------
        pd.DataFrame
            A DataFrame containing the following columns:
            - 'plate' (str):
            - 'well' (str):
            - 'average_mutation_frequency' (float):
        """
        # TODO: get_experiment_alignment_count() stub
        return pd.DataFrame()

    def get_experiment_p_value(self, experiment_id: int) -> pd.DataFrame:
        """
        Returns
        -------
        pd.DataFrame
            A DataFrame containing the following columns:
            - 'plate' (str):
            - 'well' (str):
            - 'p_value' (float):
        """
        # TODO: get_experiment_alignment_count() stub
        return pd.DataFrame()

    def get_experiment_p_adj_value(self, experiment_id: int) -> pd.DataFrame:
        """
        Returns
        -------
        pd.DataFrame
            A DataFrame containing the following columns:
            - 'plate' (str):
            - 'well' (str):
            - 'p_adj_value' (float):
        """
        # TODO: get_experiment_alignment_count() stub
        return pd.DataFrame()
