import base64

from rdkit import Chem
from rdkit.Chem import Draw, rdChemReactions


def smiles_is_empty_or_only_space(smiles_string):
    is_empty_or_only_spaces = not smiles_string or smiles_string.replace(" ", "") == ""
    return is_empty_or_only_spaces


def is_valid_smiles(smiles):
    """
    Args:
        smiles: the smiles string we would like to validate

    Returns:
        MolFromSmiles will sanitize and validat the string. It will return None upon failure

    """

    if smiles_is_empty_or_only_space(smiles):
        # Chem.MolFromSmiles accepts this as a mol! so putting in a check here
        raise ValueError("SMILES string provided is empty.")

    # MolFromSmiles will sanitize and canonicalize the molecule , defaults to True.
    # example here: https://www.rdkit.org/docs/GettingStartedInPython.html
    # Chem.MolToSmiles(Chem.MolFromSmiles('C1=CC=CN=C1'))
    # >>> 'c1ccncc1'
    # Chem.MolToSmiles(Chem.MolFromSmiles('c1cccnc1'))
    # >>> 'c1ccncc1'
    # Chem.MolToSmiles(Chem.MolFromSmiles('n1ccccc1'))
    # >>> 'c1ccncc1'
    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        return False
    else:
        return True


def convert_svg_img_to_src(svg_img):
    """
    Args:
        svg_img: input svg image generated by rdkit
        This is not a function to test whether the input provided is actually an svg input or not.
        User must use this function in conjunction with the output of rdkit only.

    Returns:
        a base64 encoded string transferable for web apps

    """
    if svg_img is None:
        raise ValueError("No svg image was provided to convert.")

    svg_base64 = base64.b64encode(svg_img.encode("utf-8")).decode("utf-8")
    svg_src = f"data:image/svg+xml;base64,{svg_base64}"
    return svg_src


def create_reaction_image(substrate_smiles: str, product_smiles: str):
    """
    Args:
        substrate_smiles: reaction substrate in smiles strings
        product_smiles: reaction product in smiles strings

    Returns:
        image

    """
    # verify the smiles string
    if not is_valid_smiles(substrate_smiles) or not is_valid_smiles(product_smiles):
        raise ValueError("Smiles String is not valid for creating an image.")

    rxn_smarts = f"{substrate_smiles}>>{product_smiles}"
    rxn = rdChemReactions.ReactionFromSmarts(rxn_smarts, useSmiles=True)

    # this function will return a raster image, and you can use
    # this in dash with an html.Img(src=img)
    # img = Draw.ReactionToImage(rxn)
    # return img

    # this option produces a svg image
    svg_img = Draw.ReactionToImage(rxn, subImgSize=(150, 150), useSVG=True)
    svg_src = convert_svg_img_to_src(svg_img)

    return svg_src


def create_mols_grid(all_smiles_strings: str):
    """
    this function is a utility function to converts all the smiles string into
    the molecular depiction in grid format. It is used solely for this app.
    Args:
        all_smiles_strings: smiles string containing all the strings semicolon delimited
        this function

    Returns:
        the svg image

    """
    if all_smiles_strings and len(all_smiles_strings) > 0:
        # Clean and split SMILES
        smiles_list = [s.strip() for s in all_smiles_strings.split(";") if s.strip()]
        mols = []
        captions = []

        # go through the list and gather the molecules and their caption/smiles strings
        for smi in smiles_list:
            # if the smiles string is in the system then it's in canonical for but just in case
            # this already makes the molecule internally
            # and probably there is double code here, but I want to keep the sematics of this separate because
            # there may be more validation added to the function then just using Chem.MolFromSmiles(smiles)
            mol = Chem.MolFromSmiles(smi)
            if mol is not None:
                mols.append(mol)
                captions.append(smi)

        if mols:
            # make a svg image for better resolution
            # MolsToGridImage is a bit more limited in terms of the layout and the padding that it has,
            # but it is better than loads of code trying to draw on the draw pad
            svg_img = Draw.MolsToGridImage(mols, molsPerRow=8, subImgSize=(200, 200), legends=captions, useSVG=True)
            svg_src = convert_svg_img_to_src(svg_img)

            return svg_src
