from enum import StrEnum

from levseq_dash.app import global_strings as gs


class MutagenesisMethod(StrEnum):
    epPCR = gs.eppcr
    SSM = gs.ssm


class DataManager:
    def __init__(self):
        """Initialize the database"""
        # TODO: database connection happens on instance load
        # ideally defined in the config file
        # BUT for now we can hardcode it here
        # connect_to_db( host, port, username, password)

    # -----------------------
    #       ADD DATA
    # -----------------------
    def add_new_experiment(
        self,
        user_id,
        experiment_name,
        experiment_time_stamp,
        experiment_date,
        substrate_cas_number: list[str],
        product_cas_number: list[str],
        assay,
        mutagenesis_method: MutagenesisMethod,  # epPCR or SSM
        experiment_content,  # or file - the contents of the csv
        geometry_content,
        parent_sequence=None,  # processed
        # file uploaded from the user
    ) -> int:
        """
        Returns
        -------
        An experiment ID is automatically generated by the database and returned for future reference.
        """
        return 0

    # ---------------------------
    #    Delete
    # ---------------------------
    def delete_experiment(self, experiment_id: int) -> bool:
        """
            Delete the experiment associated with this id

        Returns
        -------
            bool True if deleted successfully

        """

    # ---------------------------
    #    DATA RETRIEVAL: USER
    # ---------------------------
    def get_user_id(username: str) -> int:
        """
        Returns
        -------
            The unique user ID for the user
        """
        return 0

    def get_all_users(self):
        """
        Retrieve a list of all user IDs in this lab.

        Returns
        -------
        | user_id | username|

        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: ACROSS ALL EXPERIMENTS
    # ---------------------------
    def get_lab_experiments(self):
        """
        Returns list of all experiments in the lab
        -------
        | experiment_id |

        """
        return None

    def get_lab_experiments_with_meta_data(self):
        """
        Returns
        -------
        | user_id | user_name| experiment_id | experiment_name | experiment_time_stamp | experiment_date |
        substrate_cas_number | product_cas_number | assay | mutagenesis_method
        """
        return None

    def get_lab_sequences(self):
        """
        Returns
        -------
        | user_id | user_name| experiment_id | experiment_name | parent_sequence
        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: PER EXPERIMENT
    # ---------------------------
    def get_experiment_all(self, experiment_id: int):
        """
        Returns ALL 17 columns for download
        """
        return None

    def get_experiment_meta_data(self, experiment_id: int):
        """
        Returns
        -------
        |user_id | user_name | experiment_name | experiment_time_stamp | experiment_date | substrate_cas_number
        | product_cas_number | assay | mutagenesis_method
        """
        return None

    def get_experiment_dash_info(self, experiment_id: int):
        """
        Returns
        -------
        | cas_number | plate | well | alignment_count | amino_acid_substitutions | alignment_probability |
        | average_mutation_frequency | p_value | p_adj_value | x_coordinate | y_coordinate | fitness_value
        """
        return None

    def get_experiment_parent_sequence(self, experiment_id: int) -> str:
        return ""

    def get_experiment_geometry_file(self, experiment_id: int):
        """ "
        Returns file
        """
        return None

    def get_experiment_fitness_values(self, experiment_id: int):
        # I may need a separate function for this but if not data is redundant with get_experiment_stats
        """
        Returns
        -------
        | cas_number | plate | well | amino_acid_substitutions | x_coordinate | y_coordinate | fitness_value
        """
        return None

    def get_experiment_stats(self, experiment_id: int):
        """
        Returns
        -------
        | cas_number | plate | well | alignment_count | alignment_probability |
        | average_mutation_frequency | p_value | p_adj_value | x_coordinate | y_coordinate | fitness_value
        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: MISC
    # ---------------------------
    def get_assays(self):
        """
        Returns list of assays
        -------
        | assay |
        """
        return None
