import os
import random
from collections import defaultdict
from enum import StrEnum
from pathlib import Path

import pandas as pd

from levseq_dash.app import global_strings as gs
from levseq_dash.app import parser
from levseq_dash.app.experiment import Experiment, extract_experiment_meta_data
from levseq_dash.app.settings import CONFIG
from levseq_dash.app.tests.conftest import test_assay_list
from levseq_dash.app.wsexec import Query


class MutagenesisMethod(StrEnum):
    epPCR = gs.eppcr
    SSM = gs.ssm


use_db_web_service = False
load_all_experiments = True


class DataManager:
    def __init__(self):
        """Initialize the database"""
        if use_db_web_service:
            pass
            # TODO: database connection happens on instance load
            # ideally defined in the config file
            # BUT for now we can hardcode it here
            # connect_to_db( host, port, username, password)
        else:
            self.experiments_dict = defaultdict(Experiment)
            self.assay_list = test_assay_list

            # use this flag for debugging multiple files.
            # This will load all csv files in test/data
            if CONFIG["debug"]["load_all_experiments_from_disk"]:
                test_experiments = gather_all_test_experiments()
                for key in test_experiments.keys():
                    exp_file_path = test_experiments[key]["csv"]
                    geometry_file_path = test_experiments[key]["geometry"]

                    data_df = df = pd.read_csv(exp_file_path)
                    # unique_cas = df[gs.c_cas].unique()
                    # unique_plates = df[gs.c_plate].unique()
                    # filtered_df = df[(df[gs.c_cas] == unique_cas[0]) & (df[gs.c_plate] == unique_plates[0])].copy()
                    filename = os.path.basename(exp_file_path)
                    if "ssm" in str(exp_file_path):
                        mutagenesis_method = MutagenesisMethod.SSM
                    else:
                        mutagenesis_method = MutagenesisMethod.epPCR

                    assay_index = random.randrange(len(test_assay_list))
                    assay = test_assay_list[assay_index]
                    exp = Experiment(
                        data_df=data_df,
                        experiment_name=filename,
                        experiment_date="01-01-2025",
                        substrate_cas_number=generate_random_cas_numbers(),
                        product_cas_number=generate_random_cas_numbers(),
                        assay=assay,
                        mutagenesis_method=mutagenesis_method,
                        geometry_file_path=geometry_file_path,
                    )
                    self.add_experiment(exp)

        # -----------------------
        #       ADD DATA
        # -----------------------

    def add_experiment_from_ui(
        self,
        user_id,
        experiment_name,
        experiment_date,
        substrate_cas_number: list[str],
        product_cas_number: list[str],
        assay,
        mutagenesis_method: MutagenesisMethod,  # epPCR or SSM
        experiment_content_base64_string,
        geometry_content_base64_string,
        # parent_sequence=None,  # processed
    ) -> int:
        """
        Returns
        -------
        An experiment ID is automatically generated by the database and returned for future reference.
        """
        n = -1
        if use_db_web_service:
            pass
            # assay_index = assay.index(assay)
            # uid = 1
            # eid = Query(
            #     "init_load",
            #     [
            #         1,  # flask.session["uid"],
            #         "testing_upload_experiment",  # experimentName,
            #         experiment_date,  # experimentDate,
            #         4,
            #         assay_index,
            #         1,  # ,mutagenesis_method,
            #         "395683-37-1",  # substrate_cas_number,  # cas_substrate,
            #         "345905-97-7",  # product_cas_number,  # cas_product,
            #     ],
            # )  # type:ignore
            #
            # cb_csv = Query("load_file", [uid, eid, "test_csv.csv", experiment_content_base64_string])
            # cb_cif = Query("load_file", [uid, eid, "test_cif.cif", geometry_content])
        else:
            print("FileManager: add_new_experiment_from_ui")
            data_df = parser.decode_csv_file_base64_string_to_dataframe(experiment_content_base64_string)
            exp = Experiment(
                data_df=data_df,
                experiment_name=experiment_name,
                experiment_date=experiment_date,
                substrate_cas_number=substrate_cas_number,
                product_cas_number=product_cas_number,
                assay=assay,
                mutagenesis_method=mutagenesis_method,
                geometry_file_path=None,
                geometry_base64_string=geometry_content_base64_string,
            )
            n = self.add_experiment(exp)

        return n

    def add_experiment(self, exp: Experiment):
        if use_db_web_service:
            # you shouldn't be using this method with the db
            n = -1
        else:
            n = len(self.experiments_dict.items())
            self.experiments_dict[n] = exp
        return n

    # ---------------------------
    #    Delete
    # ---------------------------
    def delete_experiment(self, experiment_id: int) -> bool:
        """
            Delete the experiment associated with this id

        Returns
        -------
            bool True if deleted successfully

        """
        success = False
        if use_db_web_service:
            pass
        else:
            del self.experiments_dict[experiment_id]
            success = True

        return success

    # ---------------------------
    #    DATA RETRIEVAL: USER
    # ---------------------------
    def get_user_id(username: str) -> int:
        """
        Returns
        -------
            The unique user ID for the user
        """
        return 0

    def get_all_users(self):
        """
        Retrieve a list of all user IDs in this lab.

        Returns
        -------
        | user_id | username|

        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: ACROSS ALL EXPERIMENTS
    # ---------------------------
    def get_lab_experiments(self):
        """
        Returns list of all experiments in the lab
        -------
        | experiment_id |

        """
        experiments = []
        if use_db_web_service:
            pass
        else:
            experiments = self.experiments_dict.keys()

        return experiments

    def get_lab_experiments_with_meta_data(self):
        """
        Returns
        -------
        | user_id | user_name| experiment_id | experiment_name | upload_time_stamp | experiment_date |
        substrate_cas_number | product_cas_number | assay | mutagenesis_method
        """
        df = pd.DataFrame()
        if use_db_web_service:
            pass
        else:
            data = {key: extract_experiment_meta_data(key, exp) for key, exp in self.experiments_dict.items()}
            df = pd.DataFrame.from_dict(data, orient="index")

        return df

    def get_lab_sequences(self):
        """
        Returns
        -------
        | user_id | user_name| experiment_id | experiment_name | parent_sequence
        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: PER EXPERIMENT
    # ---------------------------
    def get_experiment(self, experiment_id: int) -> Experiment:
        # helper function
        exp = self.experiments_dict[experiment_id]
        return exp

    def get_experiment_all(self, experiment_id: int):
        """
        Returns ALL 17 columns for download
        """
        return None

    def get_experiment_meta_data(self, experiment_id: int):
        """
        Returns
        -------
        |user_id | user_name | experiment_name | upload_time_stamp | experiment_date | substrate_cas_number
        | product_cas_number | assay | mutagenesis_method
        """
        return None

    def get_experiment_dash_info(self, experiment_id: int):
        """
        Returns
        -------
        | cas_number | plate | well | alignment_count | amino_acid_substitutions | alignment_probability |
        | average_mutation_frequency | p_value | p_adj_value | x_coordinate | y_coordinate | fitness_value
        """
        return None

    def get_experiment_parent_sequence(self, experiment_id: int) -> str:
        sequence = None
        if use_db_web_service:
            pass
        else:
            sequence = self.experiments_dict[experiment_id].parent_sequence

        return sequence

    def get_experiment_geometry_file(self, experiment_id: int, geometry_form):
        """ "
        Returns file
        """
        geometry = None
        if use_db_web_service:
            pass
        else:
            if geometry_form == "bytes":
                geometry = self.experiments_dict[experiment_id].geometry_base64_bytes
            elif geometry_form == "file":
                geometry = self.experiments_dict[experiment_id].geometry_file_path

        return geometry

    def get_experiment_fitness_values(self, experiment_id: int):
        # I may need a separate function for this but if not data is redundant with get_experiment_stats
        """
        Returns
        -------
        | cas_number | plate | well | amino_acid_substitutions | x_coordinate | y_coordinate | fitness_value
        """
        return None

    def get_experiment_stats(self, experiment_id: int):
        """
        Returns
        -------
        | cas_number | plate | well | alignment_count | alignment_probability |
        | average_mutation_frequency | p_value | p_adj_value | x_coordinate | y_coordinate | fitness_value
        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: MISC
    # ---------------------------
    def get_assays(self):
        """
        Returns list of assays
        -------
        | assay |
        """
        assay_list = []
        if use_db_web_service:
            cols, rows = Query("get_assays", [])
            assay_list = [sublist[1] for sublist in rows]

            # df = pd.DataFrame(rows)
            # # cols, rows = Query("get_test_queries", [eid, uid, gid])  # type:ignore
            # cols, rows = Query("get_usernames", [])  # type:ignore
            # df_user = pd.DataFrame(data=rows, columns=cols)  # type:ignore
            # cols, rows = Query("get_mutagenesis_methods", [])  # type:ignore
            # cols_1, rows_1 = Query("get_experiments_u", [4])  # type:ignore
            # df = pd.DataFrame(rows_1)
            # eid = 102
            # gid = 2
            # cols, rows = Query("get_test_queries", [eid, 4, gid])  # type:ignore
            # # cols, rows = Query("get_user_info", [uid])  # type:ignore
            #
            # cols, rows = Query("get_variant_sequences", [1, gid])  # type:ignore
        else:
            assay_list = self.assay_list

        return assay_list

    def get_plates(self):
        return None

    def get_cas_numbers(self):
        return None


def gather_all_test_experiments():
    experiments = {}
    folder_path = Path(__file__).parent / "tests/data/"
    # Check if the folder exists
    if folder_path.exists() and folder_path.is_dir():
        # Get all files in the directory
        files_in_directory = [file for file in folder_path.iterdir() if file.is_file()]
        for file_path in files_in_directory:
            if file_path.suffix.lower() == ".csv":
                file_prefix = os.path.splitext(file_path)[0]
                # Search for a CIF file with the same prefix and additional characters
                cif_candidates = [file for file in files_in_directory if file.match(f"{file_prefix}*.cif")]
                geometry = None
                if cif_candidates:
                    geometry = cif_candidates[0]
                else:
                    # search for a pdb file
                    pdb_candidates = [file for file in files_in_directory if file.match(f"{file_prefix}*.pdb")]
                    if pdb_candidates:
                        geometry = pdb_candidates[0]

                if geometry:
                    n = len(experiments)
                    experiments[n] = {"csv": file_path, "geometry": geometry}
                    # experiments.update({"csv": file_path,
                    #                     "geometry": geometry})

    else:
        raise Exception  # (f"Directory does not exist: {folder_path}")

    return experiments


def generate_random_cas_numbers():
    num_cas = random.randint(1, 3)  # Randomly choose between 1 and 3 CAS numbers
    cas_list = []

    for _ in range(num_cas):
        part1 = random.randint(10000, 999999)  # 5-6 digits
        part2 = random.randint(10, 99)  # 2 digits
        part3 = random.randint(0, 9)  # 1-digit check number
        cas_number = f"{part1}-{part2}-{part3}"
        cas_list.append(cas_number)

    return cas_list


#
#
#
#
# # experiment_files = gather_all_test_experiments()
# # for csv_file, geometry_file in experiment_files.items():
# #     df = pd.read_csv(csv_file)
#
#
# # exp = experiment_ep_example
# # #bytes = parser.decode_base64_string_to_base64_bytes(exp.geometry_base64_string)
# # utf8_string = exp.geometry_base64_bytes.decode('utf-8')
# # file_as_string = io.StringIO(utf8_string)
# # file = exp.geometry_file
# # pdb_cif = molstar_helper.parse_molecule(exp.geometry_base64_string, fmt="cif")
# # print("done")
