import os
import random
from collections import defaultdict
from pathlib import Path

from levseq_dash.app import settings, utils
from levseq_dash.app.experiment import Experiment, MutagenesisMethod
from levseq_dash.app.tests.conftest import test_assay_list

# from levseq_dash.app.wsexec import Query


class DataManager:
    def __init__(self):
        """Initialize the database"""
        config = settings.load_config()
        self.use_db_web_service = config["debug"]["use_db_web_service"]
        if self.use_db_web_service:
            pass
            # TODO: database connection happens on instance load
            # ideally defined in the config file
            # BUT for now we can hardcode it here
            # connect_to_db( host, port, username, password)
        else:
            self.experiments_dict = defaultdict(Experiment)
            self.assay_list = test_assay_list

            # use this flag for debugging multiple files.
            # This will load all csv files in test/data
            if config["debug"]["load_all_experiments_from_disk"]:
                # function below will load test data files and their geometry from the
                # data folder and fill self.experiments_dict
                self.__load_test_experiment_data__()

    # -----------------------
    #       ADD DATA
    # -----------------------

    def add_experiment_from_ui(
        self,
        user_id,
        experiment_name,
        experiment_date,
        substrate_cas_number: list[str],
        product_cas_number: list[str],
        assay,
        mutagenesis_method: MutagenesisMethod,  # epPCR or SSM
        experiment_content_base64_string,
        geometry_content_base64_string,
        # parent_sequence=None,  # processed
    ) -> int:
        """
        Returns
        -------
        An experiment ID is automatically generated by the database and returned for future reference.
        """
        n = -1
        if self.use_db_web_service:
            pass
            # assay_index = assay.index(assay)
            # uid = 1
            # eid = Query(
            #     "init_load",
            #     [
            #         1,  # flask.session["uid"],
            #         "testing_upload_experiment",  # experimentName,
            #         experiment_date,  # experimentDate,
            #         4,
            #         assay_index,
            #         1,  # ,mutagenesis_method,
            #         "395683-37-1",  # substrate_cas_number,  # cas_substrate,
            #         "345905-97-7",  # product_cas_number,  # cas_product,
            #     ],
            # )  # type:ignore
            #
            # cb_csv = Query("load_file", [uid, eid, "test_csv.csv", experiment_content_base64_string])
            # cb_cif = Query("load_file", [uid, eid, "test_cif.cif", geometry_content])
        else:
            exp = Experiment(
                experiment_csv_data_base64_string=experiment_content_base64_string,
                experiment_name=experiment_name,
                experiment_date=experiment_date,
                substrate_cas_number=substrate_cas_number,
                product_cas_number=product_cas_number,
                assay=assay,
                mutagenesis_method=mutagenesis_method,
                geometry_file_path=None,
                geometry_base64_string=geometry_content_base64_string,
            )
            n = self.__add_experiment__(exp)

        return n

    # ---------------------------
    #    Delete
    # ---------------------------
    def delete_experiment(self, experiment_id: int) -> bool:
        """
            Delete the experiment associated with this id

        Returns
        -------
            bool True if deleted successfully

        """
        success = False
        if self.use_db_web_service:
            pass
        else:
            del self.experiments_dict[experiment_id]
            success = True

        return success

    # ---------------------------
    #    DATA RETRIEVAL: USER
    # ---------------------------
    def get_user_id(username: str) -> int:
        """
        Returns
        -------
            The unique user ID for the user
        """
        return 0

    def get_all_users(self):
        """
        Retrieve a list of all user IDs in this lab.

        Returns
        -------
        | user_id | username|

        """
        return None

    # ---------------------------
    #    DATA RETRIEVAL: ACROSS ALL EXPERIMENTS
    # ---------------------------
    # def get_lab_experiments(self):
    #     """
    #     Returns list of all experiments in the lab
    #     -------
    #     | experiment_id |
    #
    #     """
    #     # TODO:
    #     #  get_lab_experiments() may be obsolete as I use the one that also has the meta data below
    #     experiments = []
    #     if self.use_db_web_service:
    #         pass
    #     else:
    #         experiments = self.experiments_dict.keys()
    #
    #     return experiments

    def get_lab_experiments_with_meta_data(self):
        """
        Returns
        -------
        | user_id | user_name| experiment_id | experiment_name | upload_time_stamp | experiment_date |
        substrate_cas_number | product_cas_number | assay | mutagenesis_method
        """
        data_list_of_dict = []
        if self.use_db_web_service:
            # TODO:
            #  get all lab experiments ids + get metadata from each experiment
            #  OR: this can be bundled into 1 function
            #  put data together
            pass
        else:
            # get the metadata for all the experiments
            for key, exp in self.experiments_dict.items():
                exp_data = exp.exp_meta_data_to_dict()
                exp_data["experiment_id"] = key
                data_list_of_dict.append(exp_data)

            # TODO: is below faster? this has dictionary unpacking? does it have overhead?
            # data_list = [
            #     {"experiment_id": key, **exp.exp_meta_data_to_dict()}
            #     for key, exp in self.experiments_dict.items()
            # ]

        return data_list_of_dict

    def get_lab_sequences(self):
        """
        Returns
        -------
        | user_id | user_name| experiment_id | experiment_name | parent_sequence
        """
        data_list_of_dict = []
        if self.use_db_web_service:
            # get all lab sequences
            pass
        else:
            # get the metadata for all the experiments
            for key, exp in self.experiments_dict.items():
                seq_data = {"experiment_id": key, "parent_sequence": exp.parent_sequence}
                data_list_of_dict.append(seq_data)

        return data_list_of_dict

    # ---------------------------
    #    DATA RETRIEVAL: PER EXPERIMENT
    # ---------------------------
    def get_experiment(self, experiment_id: int) -> Experiment:
        # helper function
        exp = None
        if self.use_db_web_service:
            # TODO:
            #  get_experiment_meta_data
            #  get_experiment_core_data
            #  get_experiment_parent_sequence
            #  get_experiment_geometry_file
            #  return Experiment
            pass
        else:
            exp = self.experiments_dict[experiment_id]
        return exp

    def get_experiment_all(self, experiment_id: int):
        """
        Returns ALL 17 columns for download
        """
        return None

    # def get_experiment_meta_data(self, experiment_id: int):
    #     """
    #     Returns
    #     -------
    #     |user_id | user_name | experiment_name | upload_time_stamp | experiment_date | substrate_cas_number
    #     | product_cas_number | assay | mutagenesis_method
    #     """
    #     return None
    #
    # def get_experiment_core_data(self, experiment_id: int):
    #     """
    #     Returns
    #     -------
    #     | cas_number | plate | well | alignment_count | amino_acid_substitutions | alignment_probability |
    #     | average_mutation_frequency | p_value | p_adj_value | x_coordinate | y_coordinate | fitness_value
    #     """
    #     return None
    #
    # def get_experiment_parent_sequence(self, experiment_id: int) -> str:
    #     sequence = None
    #     if self.use_db_web_service:
    #         pass
    #     else:
    #         sequence = self.experiments_dict[experiment_id].parent_sequence
    #
    #     return sequence
    #
    # def get_experiment_geometry_file(self, experiment_id: int, geometry_form):
    #     """ "
    #     Returns file
    #     """
    #     geometry = None
    #     if self.use_db_web_service:
    #         pass
    #     else:
    #         if geometry_form == "bytes":
    #             geometry = self.experiments_dict[experiment_id].geometry_base64_bytes
    #         elif geometry_form == "file":
    #             geometry = self.experiments_dict[experiment_id].geometry_file_path
    #
    #     return geometry

    # ---------------------------
    #    DATA RETRIEVAL: MISC
    # ---------------------------
    def get_assays(self):
        """
        Returns list of assays
        -------
        | assay |
        """
        assay_list = []
        if self.use_db_web_service:
            # this works
            # cols, rows = Query("get_assays", [])
            # assay_list = [sublist[1] for sublist in rows]
            pass

            # df = pd.DataFrame(rows)
            # # cols, rows = Query("get_test_queries", [eid, uid, gid])  # type:ignore
            # cols, rows = Query("get_usernames", [])  # type:ignore
            # df_user = pd.DataFrame(data=rows, columns=cols)  # type:ignore
            # cols, rows = Query("get_mutagenesis_methods", [])  # type:ignore
            # cols_1, rows_1 = Query("get_experiments_u", [4])  # type:ignore
            # df = pd.DataFrame(rows_1)
            # eid = 102
            # gid = 2
            # cols, rows = Query("get_test_queries", [eid, 4, gid])  # type:ignore
            # # cols, rows = Query("get_user_info", [uid])  # type:ignore
            #
            # cols, rows = Query("get_variant_sequences", [1, gid])  # type:ignore
        else:
            assay_list = self.assay_list

        return assay_list

    # ---------------------------
    #    Private functions used internally for reading from disk not the webs service
    # ---------------------------
    def __gather_all_test_experiments__(self):
        """
        This method is only used for loading from disk for test purposes.
        It is not to be used outside of this context.
        """
        if self.use_db_web_service:
            raise Exception

        experiments = {}
        folder_path = Path(__file__).parent / "tests/data/"
        # Check if the folder exists
        if folder_path.exists() and folder_path.is_dir():
            # Get all files in the directory
            files_in_directory = [file for file in folder_path.iterdir() if file.is_file()]
            for file_path in files_in_directory:
                if file_path.suffix.lower() == ".csv":
                    file_prefix = os.path.splitext(file_path)[0]
                    # Search for a CIF file with the same prefix and additional characters
                    cif_candidates = [file for file in files_in_directory if file.match(f"{file_prefix}*.cif")]
                    geometry = None
                    if cif_candidates:
                        geometry = cif_candidates[0]
                    else:
                        # search for a pdb file
                        pdb_candidates = [file for file in files_in_directory if file.match(f"{file_prefix}*.pdb")]
                        if pdb_candidates:
                            geometry = pdb_candidates[0]

                    if geometry:
                        n = len(experiments)
                        experiments[n] = {"csv": file_path, "geometry": geometry}
                        # experiments.update({"csv": file_path,
                        #                     "geometry": geometry})

        else:
            raise Exception  # (f"Directory does not exist: {folder_path}")

        return experiments

    def __load_test_experiment_data__(self):
        """
        This method is only used for loading from disk for test purposes.
        It is not to be used outside of this context.
        """
        if self.use_db_web_service:
            raise Exception

        experiment_data_geometry_dict = self.__gather_all_test_experiments__()
        for key in experiment_data_geometry_dict.keys():
            exp_file_path = experiment_data_geometry_dict[key]["csv"]
            geometry_file_path = experiment_data_geometry_dict[key]["geometry"]

            # read the contents of the data
            # assign its method
            filename = os.path.basename(exp_file_path)
            if "ssm" in str(exp_file_path):
                mutagenesis_method = MutagenesisMethod.SSM
            else:
                mutagenesis_method = MutagenesisMethod.epPCR

            # this is test data so assign random assay and cas numbers
            assay_index = random.randrange(len(test_assay_list))
            assay = test_assay_list[assay_index]

            exp = Experiment(
                experiment_data_file_path=exp_file_path,
                experiment_name=filename,
                experiment_date="01-01-2025",
                substrate_cas_number=utils.generate_random_cas_numbers(),
                product_cas_number=utils.generate_random_cas_numbers(),
                assay=assay,
                mutagenesis_method=mutagenesis_method,
                geometry_file_path=geometry_file_path,
            )
            self.__add_experiment__(exp)

    def __add_experiment__(self, exp: Experiment):
        if self.use_db_web_service:
            raise Exception("Shouldn't be using this function with db!")

        n = len(self.experiments_dict.items())
        self.experiments_dict[n] = exp
        return n


#
#
#
#
# # experiment_files = gather_all_test_experiments()
# # for csv_file, geometry_file in experiment_files.items():
# #     df = pd.read_csv(csv_file)
#
#
# # exp = experiment_ep_example
# # #bytes = parser.decode_base64_string_to_base64_bytes(exp.geometry_base64_string)
# # utf8_string = exp.geometry_base64_bytes.decode('utf-8')
# # file_as_string = io.StringIO(utf8_string)
# # file = exp.geometry_file
# # pdb_cif = molstar_helper.parse_molecule(exp.geometry_base64_string, fmt="cif")
# # print("done")
